### ISSUE TITLE
Pipe problems

### ISSUE THREAD

**Issue by explosion-mental** [explosion-mental/dummy-poll#1]
I'm probably doing X that makes Y to pipes and results into...

**Comment by explosion-mental** [comment]
Hopefully the answer is not that far away. Is this minimal enough? and if so is it a good base to add fork/dup2/exec and X later on?

**Comment by N-R-K** [comment]
If you're getting hung, then I'm willing to bet that this is where the problem is
https://github.com/explosion-mental/dummy-poll/blob/a4630061f504c2c6d9005b921f3b17dcb5323d97/test.c#L58-L59
I won't directly answer what the problem is however, you should figure it out on your own via reading `man 7 pipe`
